
name: Run Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0,10 11 * * 1,3'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Bot
      run: |-
        python main.py
      env:
        SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
        PASSWORD_KEY: ${{secrets.PASSWORD_KEY}}

